config/routes.rb
Rails.application.routes.draw do
  resources :plans
  resources :smartphones
  resources :users
  resources :sims
  resources :requests
  resources :bams

  # Home HomePage
  root to: 'home_pages#home'
  # Request Home
  get '/requests/home/menu' => 'home_pages#request_home'
  # Follow Request
  get '/requests/home/follow_request' => 'home_pages#follow_request'
  # Show Request for user
  get '/requests/home/follow' => 'requests#show'
  # Request FAQ
  get '/requests/home/faq' => 'home_pages#faq'
  # Request downloads
  get '/requests/home/downloads' => 'home_pages#downloads'
  # Request support
  get '/requests/home/support' => 'home_pages#support'


  # Validate User
  get '/requests/home/validate' => 'requests#validate_user'
  # Validates Aproval/reject of request
  get '/requests/validations/:id' => 'requests#validations'
  # Update request for supervisor
  patch '/requests/validations/update/:id' => 'requests#update_validation'

  # Delete Action
  # smp
  get '/smartphones/delete/:id' => 'smartphones#destroy'
  # bam
  get '/bams/delete/:id' => 'bams#destroy'
  # sim
  get '/sims/delete/:id' => 'sims#destroy'
  # plan
  get '/plans/delete/:id' => 'plans#destroy'

  # Requests Forms
  # TransferLine Form
  get '/requests/forms/transferline' => 'requests#transfer_line'
  # New Form
  get '/requests/forms/new' => 'requests#new_form'
  # Save New Form
  post '/requests/forms/create/new' => 'requests#create_user'
  # Renew Form
  get '/requests/forms/renew' => 'requests#renew_form'
  # Stolen or Lost Form
  get '/requests/forms/stolenlost' => 'requests#stolen_lost'
  # Technical Service Form
  get '/requests/forms/technicalservice' => 'requests#technical_service'

  # Download Nota de pedido
  # files
  get '/requests/files/:id' => 'requests#download_file'
  # Contract
  get '/requests/contracts/:id' => 'requests#download_contract'

  # Admin
  post 'admins/login_attempt' => 'sessions#login_attempt'
  get 'admins/login_attempt' => 'sessions#login'
  get 'admins/login' => 'sessions#login'
  get 'admins/logout' => 'sessions#logout'

  # routes to register an admin
  # post 'admins/new'=> 'admins#create'
  # get 'admins/signup' => 'admins#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/smartphone.rb
class Smartphone < ApplicationRecord
  belongs_to :user, optional: true

  # Validations
  validates :model, presence: true, allow_blank: false
  validates :category, presence: true, allow_blank: false
  validates :imei, presence: true, allow_blank: false, length: { in: 14..16 }
  validates :price, presence: true, allow_blank: false
  validates :state, presence: true, allow_blank: false
  validate :valid_state
  validate :valid_category, on: :create

  private

  def valid_state
   if state != 'new' && state != 'used' && state != 'catalog'
     errors.add(:state, 'Valor del campo Estado inválido, debe ser: new, used or catalog')
   end
  end

  def valid_category
   if category != 'GE' && category != 'EJ' && category != 'VE' && category != 'PT' &&
     category != 'EE' && category != 'OO' && category != 'ALL'
     errors.add(:request, 'valor de campo Categoría inválido, debe ser: GE, EJ, VE, PT, EE, OO o ALL')
   end
  end

end

app/controllers/smartphones_controller.rb
class SmartphonesController < ApplicationController
  layout 'general_view', except: [:index, :show, :edit, :update]
  layout 'admin_view', only: [:create]

  before_action :set_smartphone, only: [:show, :edit, :update, :destroy]
  # Filter to protect page with login and session
  before_action :authenticate_user
  # check session timer
  before_action :session_expiry

  # GET /smartphones
  # GET /smartphones.json
  def index
    @search = Smartphone.search(params[:q])
    @smartphones  = @search.result
    @all_smp = all_smartphones
    @all_smp.unshift(['Todos',''])

    render layout: 'admin_view'
  end

  # GET /smartphones/1
  # GET /smartphones/1.json
  def show
    render layout: 'admin_view'
  end

  # GET /smartphones/new
  def new
    @smartphone = Smartphone.new
    render layout: 'admin_view'
  end

  # GET /smartphones/1/edit
  def edit
    render layout: 'admin_view'
  end

  # POST /smartphones
  # POST /smartphones.json
  def create
    @smartphone = Smartphone.new(smartphone_params)

    respond_to do |format|
      if @smartphone.save
        format.html { redirect_to @smartphone, notice: 'Smartphone fue creado exitosamente' }
        format.json { render :show, status: :created, location: @smartphone }
      else
        format.html { redirect_to new_smartphone_url, alert:  @smartphone.errors }
        format.json { render json: @smartphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smartphones/1
  # PATCH/PUT /smartphones/1.json
  def update
    respond_to do |format|
      if @smartphone.update(smartphone_params)
        format.html { redirect_to @smartphone, notice: 'Smartphone was successfully updated.' }
        format.json { render :show, status: :ok, location: @smartphone }
      else
        format.html { redirect_to @smartphone, alert:  @smartphone.errors}
        format.json { render json: @smartphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smartphones/1
  # DELETE /smartphones/1.json
  def destroy
    @smartphone.destroy
    respond_to do |format|
      format.html { redirect_to smartphones_url, notice: 'Smartphone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_smartphone
      @smartphone = Smartphone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def smartphone_params
      params.require(:smartphone).permit(:model, :phone_number, :code, :category, :country,
        :imei, :price, :state, :available, :renovation_at, :order, :order_name, :order_type)
    end
end

app/helpers/smartphones_helper.rb
module SmartphonesHelper
end

app/views/smartphones/_form.html.erb
<%= form_with(model: smartphone, local: true) do |form| %>

<div class="row">
  <div class="col-md-2"></div>
  <div class="well form-horizontal col-md-8">

    <div class="row">
      <p class="col-md-1 text-left">
        <strong>Id: </strong>
      </p>
      <p class="col-md-3 text-left">
        <%= @smartphone.id %>
      </p>
      <p class="user col-md-1 text-left">
        <strong>Código: </strong>
      </p>
      <p class="col-md-3">
        <%= form.text_field :code, id: :smartphone_code, class: "pull-left",
        style: "width:150px" %>
      </p>
      <p class=" user col-md-1 text-left">
        <strong>Imei: </strong>
      </p>
      <p class="col-md-3">
        <%= form.text_field :imei, id: :smartphone_imei, class: "pull-left",
        style: "width:150px" %>
      </p>
    </div>

    <div class="row">
      <p class="col-md-1 text-left">
        <strong>Modelo: </strong>
      </p>
      <p class="user col-md-3">
        <%= form.text_field :model, id: :smartphone_model, class: "pull-left",
        style: "width:150px" %>
      </p>
      <p class="user col-md-1 text-left">
        <strong>Categoría: </strong>
      </p>
      <p class="user col-md-3">
        <%= form.select :category, [['Gerente', 'GE'], ['Subgerente' , 'EJ'],
        ['Jefes', 'PT'], ['Vendedores','VE'], ['Operarios','OO'], ['Otros','EE'],
        ['Libre','ALL']], {}, {id: "smartphone_category", style: "width:150px", class: "pull-left"}%>
      </p>
      <p class=" user col-md-1 text-left">
        <strong>Estado: </strong>
      </p>
      <p class=" user col-md-3">
        <%= form.select :state, [['Catalogo', 'catalog'], ['Nuevo', 'new'], ['Usado' , 'used' ]],
        {}, {id: :smartphone_state, style: "width:150px", class: "pull-left"}%>
      </p>
    </div>

    <div class="row">
      <p class="col-md-1 text-left">
        <strong>n° Teléfono:</strong>
      </p>
      <p class="col-md-3">
        <%= form.text_field :phone_number, id: :smartphone_phone_number, class: "pull-left",
        style: "width:150px"  %>
      </p>
      <p class="user col-md-1 text-left">
        <strong>Precio: </strong>
      </p>
      <p class="col-md-3">
        <%= form.number_field :price, id: :smartphone_price, class: "pull-left",
        style: "width:150px"  %>
      </p>
      <p class=" user col-md-1 text-left">
        <strong>Disponible: </strong>
      </p>
      <p class="col-md-3">
        <%= form.select :available, [['True', true], ['False', false]],
        {}, {id: :smartphone_available, style: "width:150px", class: "pull-left"}%>
      </p>
    </div>

    <div class="row">
      <p class="user col-md-1 text-left">
        <strong>Pais:</strong>
      </p>
      <p class="col-md-3">
        <%= form.select :country, [['Chile', 'CHL']],
        {}, {id: :smartphone_country, style: "width:150px", class: "pull-left"}%>
      </p>
      <p class="col-md-1 text-left">
        <strong>Renovación:</strong>
      </p>
      <p class="col-md-7">
        <%= form.datetime_select :renovation_at, {order: [:day, :month, :year],
          default: 24.months.from_now}, {id: :smartphone_renovation_at}  %>
      </p>
    </div>

    <br>
    <div class="actions">
      <% if params[:action] == 'new'%>
        <%= form.submit 'Crear', onclick: "return confirm('Está seguro que desea Crear el Smartphone')",
        class: "btn btn-primary btn-md" %>
      <% else %>
        <%= form.submit 'Editar', onclick: "return confirm('Está seguro que desea Editar el Smartphone')",
        class: "btn btn-primary btn-md" %>
      <% end %>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>

<% end %>

app/views/smartphones/edit.html.erb
<hr>
<h3><strong>Editor Smartphone</strong></h3>
<hr>

<%= render 'form', smartphone: @smartphone %>

<%= link_to 'Smartphone', @smartphone %> |
<%= link_to 'Smartphones', smartphones_path %>

app/views/smartphones/index.html.erb
<style>
  .input {
    margin-top: 3px;
    margin-bottom: 5px;
  }
  .alert {
    margin-top: 5px;
    display:inline-block;
    vertical-align: middle;
    height: 50%;
    padding: 1px;
    margin-top: 1%;
    margin-bottom: 1%;
  }
  label {
    padding-top: 7px;
  }
  hr {
    margin-top: 3px;
    margin-bottom: 3px;
    padding: 0px;
  }

  h3{
    margin-top: 12px;
    margin-bottom: 12px;
    padding: 0px;
  }

  .btn {
    margin-top: 10px;
    margin-bottom: 10px;
  }
</style>

<%= render partial: '/layouts/smp_filter' %>

<div class= "titulo">
  <hr>
  <h3><strong>Smartphones</strong></h3>
  <hr>
</div>
<% if notice %>
  <div class="row">
    <p class="col-md-4 text-left"></p>
    <p class="user col-md-4 alert alert-success">
         <strong> El Smartphone fue eliminado exitosamente </strong>
    </p>
    <p class=" user col-md-4 text-left"></p>
  </div>
<% end %>

<div class="container-fluid">
  <div class="table-responsive">
    <table class="table table-hover table-condensed">
      <thead class="thead-dark">
        <tr>
          <th scope="col" class= text-center><%= sort_link @search, :id, "id"%></th>
          <th scope="col" class= text-center><%= sort_link @search, :model, "Modelo"%> </th>
          <th scope="col" class= text-center><%= sort_link @search, :category, "Categoria"%></th>
          <th scope="col" class= text-center><%= sort_link @search, :state, "Estado"%></th>
          <th scope="col" class= text-center><%= sort_link @search, :available, "Disponible"%></th>
          <th scope="col" class= text-center><%= sort_link @search, :renovation_at, "Fecha Renovación"%></th>
          <th scope="col" class= text-center>Número Telefónico</th>
          <th scope="col" class= text-center>Smartphone</th>
          <th scope="col" class= text-center>Editar</th>
          <th scope="col" class= text-center>Eliminar</th>
        </tr>
      </thead>

      <tbody>
        <% @smartphones.each do |smartphone| %>
          <tr>
            <td><%= smartphone.id %></td>
            <td><%= smartphone.model %></td>
            <td><%= smartphone.category %></td>
            <td><%= smartphone.state %></td>
            <td><%= smartphone.available %></td>
            <% if smartphone.renovation_at %>
            <td><%= smartphone.renovation_at.strftime('%d/%m/%Y') %></td>
            <% else %>
            <td><%= "" %></td>
            <%end%>
            <td><%= smartphone.phone_number %></td>
            <td><%= link_to 'Smartphone', smartphone %></td>
            <td><%= link_to 'Editar', edit_smartphone_path(smartphone) %></td>
            <td><%= link_to 'Eliminar', '/smartphones/delete/'+smartphone.id.to_s,
            onclick: "return confirm('Está seguro que desea Eliminar el Smartphone con id "+smartphone.id.to_s+ "')" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<hr>
<%= link_to 'Crear Smartphone', new_smartphone_path, class: "btn btn-primary btn-md" %>
<hr>
<br>

app/views/smartphones/new.html.erb
<hr>
<h3><strong>Crear Smartphone</strong></h3>
<hr>

<%= render 'form', smartphone: @smartphone %>

<% if alert %>
<div class="row">
  <p class="col-md-2 text-left"></p>
  <p class="user col-md-8 alert alert-danger">
    <strong> Los siguientes errores impidieron finalizar la creación exitosamente: </strong>
    <% alert.each_pair do |k, v| %>
      <%= " | El campo "+k+" tiene el siguiente error: "+v[0] %>
    <% end %>
  </p>
  <p class=" user col-md-2 text-left"></p>
</div>
<% end %>

<%= link_to 'Smartphones', smartphones_path %>

app/views/smartphones/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Solicitud Celulares CCU</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <style>
      p {
        margin: 1px 0px 1px 0px;
      }
      .alert {
        margin-top: 5px;
        display:inline-block;
        vertical-align: middle;
        height: 50%;
        padding: 1px;
        margin-top: 1%;
        margin-bottom: 1%;
      }
  </style>

</head>

<body>

  <hr>
  <h3><strong>Detalle Smartphone</strong></h3>
  <hr>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="well form-horizontal col-md-8">

      <div class="row">
        <p class="col-md-4 text-left">
          <strong>Id: </strong>
          <%= @smartphone.id %>
        </p>
        <p class="user col-md-4 text-left">
          <strong>Código: </strong>
          <%= @smartphone.code %>
        </p>
        <p class=" user col-md-4 text-left">
          <strong>Imei: </strong>
          <%= @smartphone.imei %>
        </p>
      </div>

      <div class="row">
        <p class="col-md-4 text-left">
          <strong>Modelo: </strong>
          <%= @smartphone.model %>
        </p>
        <p class="user col-md-4 text-left">
          <strong>Categoría: </strong>
          <%= @smartphone.category %>
        </p>
        <p class=" user col-md-4 text-left">
          <strong>Estado: </strong>
          <%= @smartphone.state %>
        </p>
      </div>

      <div class="row">
        <p class="col-md-4 text-left">
          <strong>n° Teléfono: </strong>
          <%= @smartphone.phone_number %>
        </p>
        <p class="user col-md-4 text-left">
          <strong>Precio: </strong>
          <%= '$'+@smartphone.price.to_s %>
        </p>
        <p class=" user col-md-4 text-left">
          <strong>Disponible: </strong>
          <%= @smartphone.available %>
        </p>
      </div>

      <div class="row">
        <p class="user col-md-4 text-left">
          <strong>Pais:</strong>
          <%= @smartphone.country %>
        </p>
          <p class="col-md-4 text-left">
            <% if @smartphone.renovation_at %>
              <strong>Fecha renovación:</strong>
              <%= @smartphone.renovation_at.strftime('%d/%m/%Y') %>
            <% end %>
          </p>
          <p class=" user col-md-4 text-left"> </p>
      </div>

      <hr>
      <%= link_to 'Editar', edit_smartphone_path(@smartphone) %> |
      <%= link_to 'Smartphones', smartphones_path %>

    </div>
    <div class="col-md-2"></div>
  </div>

  <% if notice %>
  <div class="row">
    <p class="col-md-4 text-left"></p>
    <p class="user col-md-4 alert alert-success">
         <strong> <%=notice%> </strong>
    </p>
    <p class=" user col-md-4 text-left"></p>
  </div>
  <% elsif alert %>
  <div class="row">
    <p class="col-md-2 text-left"></p>
    <p class="user col-md-8 alert alert-danger">
      <strong> Los siguientes errores impidieron finalizar la edición exitosamente: </strong>
      <% alert.each_pair do |k, v| %>
        <%= " | El campo "+k+" tiene el siguiente error: "+v[0] %>
      <% end %>
    </p>
    <p class=" user col-md-2 text-left"></p>
  </div>
  <% end %>

</body>
</html>