config/routes.rb
Rails.application.routes.draw do
  resources :plans
  resources :smartphones
  resources :users
  resources :sims
  resources :requests
  resources :bams

  # Home HomePage
  root to: 'home_pages#home'
  # Request Home
  get '/requests/home/menu' => 'home_pages#request_home'
  # Follow Request
  get '/requests/home/follow_request' => 'home_pages#follow_request'
  # Show Request for user
  get '/requests/home/follow' => 'requests#show'
  # Request FAQ
  get '/requests/home/faq' => 'home_pages#faq'
  # Request downloads
  get '/requests/home/downloads' => 'home_pages#downloads'
  # Request support
  get '/requests/home/support' => 'home_pages#support'


  # Validate User
  get '/requests/home/validate' => 'requests#validate_user'
  # Validates Aproval/reject of request
  get '/requests/validations/:id' => 'requests#validations'
  # Update request for supervisor
  patch '/requests/validations/update/:id' => 'requests#update_validation'

  # Delete Action
  # smp
  get '/smartphones/delete/:id' => 'smartphones#destroy'
  # bam
  get '/bams/delete/:id' => 'bams#destroy'
  # sim
  get '/sims/delete/:id' => 'sims#destroy'
  # plan
  get '/plans/delete/:id' => 'plans#destroy'

  # Requests Forms
  # TransferLine Form
  get '/requests/forms/transferline' => 'requests#transfer_line'
  # New Form
  get '/requests/forms/new' => 'requests#new_form'
  # Save New Form
  post '/requests/forms/create/new' => 'requests#create_user'
  # Renew Form
  get '/requests/forms/renew' => 'requests#renew_form'
  # Stolen or Lost Form
  get '/requests/forms/stolenlost' => 'requests#stolen_lost'
  # Technical Service Form
  get '/requests/forms/technicalservice' => 'requests#technical_service'

  # Download Nota de pedido
  # files
  get '/requests/files/:id' => 'requests#download_file'
  # Contract
  get '/requests/contracts/:id' => 'requests#download_contract'

  # Admin
  post 'admins/login_attempt' => 'sessions#login_attempt'
  get 'admins/login_attempt' => 'sessions#login'
  get 'admins/login' => 'sessions#login'
  get 'admins/logout' => 'sessions#logout'

  # routes to register an admin
  # post 'admins/new'=> 'admins#create'
  # get 'admins/signup' => 'admins#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  has_many :requests
  has_one :bam
  has_one :plan
  has_one :smarthphone
  has_one :sim

  # Validations
  validates :name, presence: true, allow_blank: false
  validates :national_id, presence: true, allow_blank: false
  validates :jobtitle, presence: true, allow_blank: false
  validates :email, presence: true, uniqueness: true, allow_blank: true,
  email_format: { message: 'Invalid email format' }
  validates :supervisor, presence: true, allow_blank: true
  validates :supervisor_email, presence: true, allow_blank: true,
  email_format: { message: 'Invalid email format' }
  validates :deptname, presence: true, allow_blank: false
  validates :country, presence: true, allow_black: false
  validates :smartphone_id, :allow_blank => true, :uniqueness => true
  validates :bam_id, :allow_blank => true, :uniqueness => true
  validates :sim_id, :allow_blank => true, :uniqueness => true
  validates :plan_id, :allow_blank => true, :uniqueness => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'general_view' , except: [:create_user, :index, :show, :edit, :update, :new]
  layout 'admin_view', only: [:create]

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # Filter to protect page with login and session
  before_action :authenticate_user
  # check session timer
  before_action :session_expiry

  # GET /users
  # GET /users.json
  def index
    @search = User.search(params[:q])
    @users  = @search.result
    render layout: 'admin_view'
  end

  # GET /users/1
  # GET /users/1.json
  def show
    render layout: 'admin_view'
  end

  # GET /users/new
  def new
    @user = User.new
    render layout: 'admin_view'
  end

  # GET /users/1/edit
  def edit
    render layout: 'admin_view'
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuario fue creado exitosamente'}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { redirect_to new_user_url, alert:  @user.errors }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      puts(params)
      if @user.update(user_params)
        puts('exito')
        format.html { redirect_to @user, notice: 'Usuario fue editado exitosamente' }
        format.json { render :show, status: :ok, location: @user }
      else
        puts('fracaso')
        format.html { redirect_to @user, alert:  @user.errors }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuario fue borrado exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:national_id, :name, :last_name, :email, :country,
        :jobtitle, :job_family, :company, :supervisor, :supervisor_email,
        :supervisor_jobtitle, :jobcode, :location, :deptname, :smartphone_id,
        :bam_id, :sim_id, :plan_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<style>
  .text_area {
    vertical-align: top;
  }
</style>

<%= form_with(model: user, local: true) do |form| %>

<div class="row">
  <div class="col-md-3"></div>
  <div class="well form-horizontal col-md-6">

    <div class="row">
      <p class="col-md-2 text-left">
        <strong>Smartphone Id: </strong>
      </p>
      <p class="col-md-4">
        <%= form.number_field :smartphone_id, id: :user_smartphone_id,
        class: "pull-left", style: "width:120px" %>
      </p>
      <p class="col-md-2 text-left">
        <strong>Bam Id: </strong>
      </p>
      <p class="col-md-4">
        <%= form.number_field :bam_id, id: :user_bam_id, class: "pull-left",
        style: "width:120px"  %>
      </p>
    </div>

    <div class="row">
      <p class="col-md-2 text-left">
        <strong>Plan Id: </strong>
      </p>
      <p class="col-md-4">
        <%= form.number_field :plan_id, id: :user_plan_id, class: "pull-left",
        style: "width:120px"  %>
      </p>
      <p class="col-md-2 text-left">
        <strong>Sim Id: </strong>
      </p>
      <p class="col-md-4">
        <%= form.number_field :sim_id, id: :user_sim_id, class: "pull-left",
        style: "width:120px"  %>
      </p>
    </div>

    <br>
    <div class="actions">
      <% if params[:action] == 'new'%>
        <%= form.submit 'Crear', onclick: "return confirm('Está seguro que desea Crear el Usuario')",
        class: "btn btn-primary btn-md" %>
      <% else %>
        <%= form.submit 'Editar', onclick: "return confirm('Está seguro que desea Editar el Usuario')",
        class: "btn btn-primary btn-md" %>
      <% end %>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>

<% end %>

app/views/users/edit.html.erb
<hr>
<h3><strong>Editor Usuario</strong></h3>
<hr>

<%= render 'form', user: @user %>

<%= link_to 'Usuario', @user %> |
<%= link_to 'Usuarios', users_path %>

app/views/users/index.html.erb
<style>
  .alert {
    margin-top: 5px;
    display:inline-block;
    vertical-align: middle;
    height: 50%;
    padding: 1px;
    margin-top: 1%;
    margin-bottom: 1%;
  }
  label {
    padding-top: 7px;
  }
  hr {
    margin-top: 3px;
    margin-bottom: 3px;
    padding: 0px;
  }
  h3{
    margin-top: 12px;
    margin-bottom: 12px;
    padding: 0px;
  }
  .btn {
    margin-top: 10px;
    margin-bottom: 10px;
  }
</style>

<%= render partial: '/layouts/user_filter' %>

<div class= "titulo">
  <hr>
  <h3><strong>Usuarios</strong></h3>
  <hr>
</div>

<div class="container-fluid">
  <div class="table-responsive">
    <table class="table table-hover table-condensed">
      <thead class="thead-dark">
        <tr>
          <th scope="col" class= text-center><%= sort_link @search, :id, "id"%></th>
          <th scope="col" class= text-center><%= sort_link @search, :national_id, "RUT"%></th>
          <th scope="col" class= text-center><%= sort_link @search, :name, "Nombre"%> </th>
          <th scope="col" class= text-center><%= sort_link @search, :last_name, "Apellidos"%> </th>
          <th scope="col" class= text-center><%= sort_link @search, :jobtitle, "Cargo"%></th>
          <th scope="col" class= text-center><%= sort_link @search, :job_family, "Familia Cargo"%></th>
          <th scope="col" class= text-center><%= sort_link @search, :company, "Empresa"%> </th>
          <th scope="col" class= text-center><%= sort_link @search, :deptname, "Centro de Costos"%></th>
          <th scope="col" class= text-center><%= sort_link @search, :location, "Ubicación"%></th>
          <th scope="col" class= text-center>Usuario</th>
          <th scope="col" class= text-center>Editar</th>
          <th scope="col" class= text-center>Smartphone</th>
          <th scope="col" class= text-center>Bam</th>
          <th scope="col" class= text-center>Plan</th>
          <th scope="col" class= text-center>Sim</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.national_id %></td>
            <td><%= user.name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.jobtitle %></td>
            <td><%= user.job_family %></td>
            <td><%= user.company %></td>
            <td><%= user.deptname %></td>
            <td><%= user.location %></td>
            <td><%= link_to 'Usuario', user %></td>
            <td><%= link_to 'Editar', edit_user_path(user) %></td>
            <td>
              <% if user.smartphone_id.present? && Smartphone.find_by_id(user.smartphone_id)%>
                <%= link_to 'Smp', smartphone_path(user.smartphone_id) %>
              <%end%>
            </td>
            <td>
              <% if user.bam_id.present? && Bam.find_by_id(user.bam_id)%>
                <%= link_to 'Bam', bam_path(user.bam_id) %>
              <%end%>
            </td>
            <td>
              <% if user.plan_id.present? && Plan.find_by_id(user.plan_id)%>
                <%= link_to 'Plan', plan_path(user.plan_id) %>
              <%end%>
            </td>
            <td>
              <% if user.sim_id.present? && Sim.find_by_id(user.sim_id)%>
                <%= link_to 'Sim', sim_path(user.sim_id) %>
              <%end%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

app/views/users/new.html.erb
<hr>
<h3><strong>Crear Usuario</strong></h3>
<hr>

<%= render 'form', user: @user %>

<% if alert %>
<div class="row">
  <p class="col-md-2 text-left"></p>
  <p class="user col-md-8 alert alert-danger">
    <strong> Los siguientes errores impidieron finalizar la creación exitosamente: </strong>
    <% alert.each_pair do |k, v| %>
      <%= " | El campo "+k+" tiene el siguiente error: "+v[0] %>
    <% end %>
  </p>
  <p class=" user col-md-2 text-left"></p>
</div>
<% end %>

<%= link_to 'Usuarios', users_path %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Solicitud Celulares CCU</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <style>
      p {
        margin: 1px 0px 1px 0px;
      }
      .alert {
        margin-top: 5px;
        display:inline-block;
        vertical-align: middle;
        height: 50%;
        padding: 1px;
        margin-top: 1%;
        margin-bottom: 1%;
      }
  </style>

</head>

<body>

<hr>
<h3><strong>Información Usuario</strong></h3>
<hr>

<div class="row">
  <div class="col-md-3"></div>
    <div class="well form-horizontal col-md-6">

      <div class="row">
        <p class="col-md-6 text-left">
          <strong>Nombre:</strong>
          <%= @user.name %>
        </p>

        <p class="col-md-6 text-left">
          <strong>Apellidos:</strong>
          <%= @user.last_name %>
        </p>
    </div>

    <div class="row">
      <p class="col-md-6 text-left">
        <strong>Rut:</strong>
        <%= @user.national_id %>
      </p>

      <p class="col-md-6 text-left">
        <strong>e-mail:</strong>
        <%= @user.email %>
      </p>
    </div>

    <div class="row">
      <p class="col-md-6 text-left">
        <strong>Cargo:</strong>
        <%= @user.jobtitle %>
      </p>

      <p class="col-md-6 text-left">
        <strong>Familia de Cargo:</strong>
        <%= @user.jobtitle %>
      </p>
    </div>

    <div class="row">
      <p class="col-md-6 text-left">
        <strong>Empresa:</strong>
        <%= @user.company %>
      </p>

      <p class="col-md-6 text-left">
        <strong>País:</strong>
        <%= @user.country %>
      </p>
    </div>

    <div class="row">
      <p class="col-md-6 text-left">
        <strong>Supervisor:</strong>
        <%= @user.supervisor %>
      </p>

      <p class="col-md-6 text-left">
        <strong>Correo Supervisor:</strong>
        <%= @user.supervisor_email %>
      </p>
    </div>

    <div class="row">
      <p class="col-md-6 text-left">
        <strong>Centro de Costos:</strong>
        <%= @user.deptname %>
      </p>

      <p class="col-md-6 text-left">
        <strong>Ubicación:</strong>
        <%= @user.location %>
      </p>
    </div>

    <div class="row">
      <p class="col-md-6 text-left">
        <strong>Smartphone Asignado:</strong>
        <%=@user.smartphone_id%>
      </p>

      <p class="col-md-6 text-left">
        <strong>Bam Asignado:</strong>
        <%=@user.bam_id%>
      </p>
    </div>

    <div class="row">
      <p class="col-md-6 text-left">
        <strong>Sim Asignada:</strong>
        <%=@user.sim_id%>
      </p>

      <p class="col-md-6 text-left">
        <strong>Plan Asignado:</strong>
        <%=@user.plan_id%>
      </p>
    </div>

    <hr>
    | <%= link_to 'Editar', edit_user_path  %> | <%= link_to 'Usuarios', users_path  %> |
    <%= link_to 'Solicitudes', requests_path+"?q[national_id_cont]="+@user.national_id+"&commit=Filtrar"%> |

    </div>
  <div class="col-md-3"></div>
</div>

<% if notice %>
<div class="row">
  <p class="col-md-4 text-left"></p>
  <p class="user col-md-4 alert alert-success">
       <strong> <%=notice%>  </strong>
  </p>
  <p class=" user col-md-4 text-left"></p>
</div>
<% elsif alert %>
<div class="row">
  <p class="col-md-2 text-left"></p>
  <p class="user col-md-8 alert alert-danger">
    <strong> Los siguientes errores impidieron finalizar la edición exitosamente: </strong>
    <% alert.each_pair do |k, v| %>
      <%= " | El campo "+k+" tiene el siguiente error: "+v[0] %>
    <% end %>
  </p>
  <p class=" user col-md-2 text-left"></p>
</div>
<% end %>

</body>
</html>