config/routes.rb
Rails.application.routes.draw do
  resources :plans
  resources :smartphones
  resources :users
  resources :sims
  resources :requests
  resources :bams

  # Home HomePage
  root to: 'home_pages#home'
  # Request Home
  get '/requests/home/menu' => 'home_pages#request_home'
  # Follow Request
  get '/requests/home/follow_request' => 'home_pages#follow_request'
  # Show Request for user
  get '/requests/home/follow' => 'requests#show'
  # Request FAQ
  get '/requests/home/faq' => 'home_pages#faq'
  # Request downloads
  get '/requests/home/downloads' => 'home_pages#downloads'
  # Request support
  get '/requests/home/support' => 'home_pages#support'


  # Validate User
  get '/requests/home/validate' => 'requests#validate_user'
  # Validates Aproval/reject of request
  get '/requests/validations/:id' => 'requests#validations'
  # Update request for supervisor
  patch '/requests/validations/update/:id' => 'requests#update_validation'

  # Delete Action
  # smp
  get '/smartphones/delete/:id' => 'smartphones#destroy'
  # bam
  get '/bams/delete/:id' => 'bams#destroy'
  # sim
  get '/sims/delete/:id' => 'sims#destroy'
  # plan
  get '/plans/delete/:id' => 'plans#destroy'

  # Requests Forms
  # TransferLine Form
  get '/requests/forms/transferline' => 'requests#transfer_line'
  # New Form
  get '/requests/forms/new' => 'requests#new_form'
  # Save New Form
  post '/requests/forms/create/new' => 'requests#create_user'
  # Renew Form
  get '/requests/forms/renew' => 'requests#renew_form'
  # Stolen or Lost Form
  get '/requests/forms/stolenlost' => 'requests#stolen_lost'
  # Technical Service Form
  get '/requests/forms/technicalservice' => 'requests#technical_service'

  # Download Nota de pedido
  # files
  get '/requests/files/:id' => 'requests#download_file'
  # Contract
  get '/requests/contracts/:id' => 'requests#download_contract'

  # Admin
  post 'admins/login_attempt' => 'sessions#login_attempt'
  get 'admins/login_attempt' => 'sessions#login'
  get 'admins/login' => 'sessions#login'
  get 'admins/logout' => 'sessions#logout'

  # routes to register an admin
  # post 'admins/new'=> 'admins#create'
  # get 'admins/signup' => 'admins#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/sim.rb
class Sim < ApplicationRecord
  belongs_to :user, optional: true

  # Validations
  validates :phone_number, presence: true, allow_blank: false, length: { in: 8..11 }
  validates :state, presence: true, allow_blank: false
  validate :valid_state


  private

  def valid_state
    if state != 'new' && state != 'used'
      errors.add(:state, 'invalid request field, must be: new or used')
    end
  end

end

app/controllers/sims_controller.rb
class SimsController < ApplicationController
  layout 'general_view', except: [:index, :show, :edit, :update, :new]
  layout 'admin_view', only: [:create]

  before_action :set_sim, only: [:show, :edit, :update, :destroy]
  # Filter to protect page with login and session
  before_action :authenticate_user
  # check session timer
  before_action :session_expiry

  # GET /sims
  # GET /sims.json
  def index
    @sims = Sim.all
    @search = Sim.search(params[:q])
    @sims  = @search.result

    render layout: 'admin_view'
  end

  # GET /sims/1
  # GET /sims/1.json
  def show
    render layout: 'admin_view'
  end

  # GET /sims/new
  def new
    @sim = Sim.new
    render layout: 'admin_view'
  end

  # GET /sims/1/edit
  def edit
    render layout: 'admin_view'
  end

  # POST /sims
  # POST /sims.json
  def create
    @sim = Sim.new(sim_params)

    respond_to do |format|
      if @sim.save
        format.html { redirect_to @sim, notice: 'Sim fue creada exitosamente' }
        format.json { render :show, status: :created, location: @sim }
      else
        format.html { redirect_to new_sim_url, alert:  @sim.errors }
        format.json { render json: @sim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sims/1
  # PATCH/PUT /sims/1.json
  def update
    respond_to do |format|
      if @sim.update(sim_params)
        format.html { redirect_to @sim, notice: 'Sim fue editada exitosamente' }
        format.json { render :show, status: :ok, location: @sim }
      else
        format.html  { redirect_to @sim, alert:  @sim.errors }
        format.json { render json: @sim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sims/1
  # DELETE /sims/1.json
  def destroy
    @sim.destroy
    respond_to do |format|
      format.html { redirect_to sims_url, notice: 'Sim fue borrada exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sim
      @sim = Sim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sim_params
      params.require(:sim).permit(:phone_number, :serial_number, :country, :state,
        :available, :order, :order_name, :order_type)
    end
end

app/helpers/sims_helper.rb
module SimsHelper
end

app/views/sims/_form.html.erb
<style>
  .text_area {
    vertical-align: top;
  }
</style>

<%= form_with(model: sim, local: true) do |form| %>

<div class="row">
  <div class="col-md-2"></div>
  <div class="well form-horizontal col-md-8">

    <div class="row">
      <p class="col-md-1 text-left">
        <strong>Id: </strong>
      </p>
      <p class="col-md-3 text-left">
        <%= @sim.id %>
      </p>
      <p class="user col-md-1 text-left">
        <strong>n° Serie: </strong>
      </p>
      <p class="user col-md-3 text-left">
        <%= form.text_field :serial_number, id: :sim_serial_number, class: "pull-left",
        style: "width:100px" %>
      </p>
      <p class=" user col-md-1 text-left">
        <strong>n° Teléfono: </strong>
      </p>
      <p class=" user col-md-3 text-left">
        <%= form.text_field :phone_number, id: :sim_phone_number, class: "pull-left",
        style: "width:100px" %>
      </p>
    </div>

    <div class="row">
      <p class=" user col-md-1 text-left">
        <strong>Estado: </strong>
      </p>
      <p class=" user col-md-3">
        <%= form.select :state, [['Nuevo','new'], ['Usado','used']], {},
        {id: :sim_state, style: "width:100px", class: "pull-left"}%>
      </p>
      <p class="col-md-1 text-left">
        <strong>Disponible: </strong>
      </p>
      <p class=" user col-md-3">
        <%= form.select :available, [['True', true], ['False', false]],
        {}, {id: :sim_available, style: "width:100px", class: "pull-left"}%>
      </p>
      <p class=" user col-md-1 text-left">
        <strong>Pais:</strong>
      </p>
      <p class=" user col-md-3 ">
        <%= form.select :country, [['Chile', 'CHL']],
        {}, {id: :sim_country, style: "width:100px", class: "pull-left"}%>
      </p>
    </div>

    <br>
    <div class="actions">
      <% if params[:action] == 'new'%>
        <%= form.submit 'Crear', onclick: "return confirm('Está seguro que desea Crear la Sim')",
        class: "btn btn-primary btn-md" %>
      <% else %>
        <%= form.submit 'Editar', onclick: "return confirm('Está seguro que desea Editar la Sim')",
        class: "btn btn-primary btn-md" %>
      <% end %>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>


<% end %>

app/views/sims/edit.html.erb
<hr>
<h3><strong>Editor Sim</strong></h3>
<hr>

<%= render 'form', sim: @sim %>

<%= link_to 'Sim', @sim %> |
<%= link_to 'Sims', sims_path %>

app/views/sims/index.html.erb
<style>
  .alert {
    margin-top: 5px;
    display:inline-block;
    vertical-align: middle;
    height: 50%;
    padding: 1px;
    margin-top: 1%;
    margin-bottom: 1%;
  }
  label {
    padding-top: 7px;
  }
  hr {
    margin-top: 3px;
    margin-bottom: 3px;
    padding: 0px;
  }
  h3{
    margin-top: 12px;
    margin-bottom: 12px;
    padding: 0px;
  }
  .btn {
    margin-top: 10px;
    margin-bottom: 10px;
  }
</style>

<%= render partial: '/layouts/sim_filter' %>

<div class= "titulo">
  <hr>
  <h3><strong>Sims</strong></h3>
  <hr>
</div>

<% if notice %>
  <div class="row">
    <p class="col-md-4 text-left"></p>
    <p class="user col-md-4 alert alert-success">
         <strong> La Sim fue eliminada exitosamente </strong>
    </p>
    <p class=" user col-md-4 text-left"></p>
  </div>
<% end %>

<div class="container-fluid">
  <div class="table-responsive">
    <table class="table table-hover table-condensed">
      <thead class="thead-dark">
        <tr>
          <th scope="col" class= text-center><%= sort_link @search, :id, "id"%></th>
          <th scope="col" class= text-center><%= sort_link @search, :serial_number, "n° de Serie"%> </th>
          <th scope="col" class= text-center><%= sort_link @search, :phone_number, "n° de Teléfono"%></th>
          <th scope="col" class= text-center><%= sort_link @search, :available, "Disponible"%> </th>
          <th scope="col" class= text-center><%= sort_link @search, :state, "Estado"%></th>
          <th scope="col" class= text-center>Sim</th>
          <th scope="col" class= text-center>Editar</th>
          <th scope="col" class= text-center>Eliminar</th>
        </tr>
      </thead>

      <tbody>
        <% @sims.each do |sim| %>
          <tr>
            <td><%= sim.id %></td>
            <td><%= sim.serial_number %></td>
            <td><%= sim.phone_number %></td>
            <td><%= sim.available %></td>
            <td><%= sim.state %></td>
            <td><%= link_to 'Sim', sim %></td>
            <td><%= link_to 'Editar', edit_sim_path(sim) %></td>
            <td><%= link_to 'Eliminar', '/sims/delete/'+sim.id.to_s,
            onclick: "return confirm('Está seguro que desea Eliminar la Sim con id "+sim.id.to_s+ "')" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<hr>
<%= link_to 'Crear Sim', new_sim_path, class: "btn btn-primary btn-md" %>
<hr>
<br>

app/views/sims/new.html.erb
<hr>
<h3><strong>Crear Sim</strong></h3>
<hr>

<%= render 'form', sim: @sim %>

<% if alert %>
<div class="row">
  <p class="col-md-2 text-left"></p>
  <p class="user col-md-8 alert alert-danger">
    <strong> Los siguientes errores impidieron finalizar la creación exitosamente: </strong>
    <% alert.each_pair do |k, v| %>
      <%= " | El campo "+k+" tiene el siguiente error: "+v[0] %>
    <% end %>
  </p>
  <p class=" user col-md-2 text-left"></p>
</div>
<% end %>

<%= link_to 'Sims', sims_path %>

app/views/sims/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Solicitud Celulares CCU</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <style>
      p {
        margin: 1px 0px 1px 0px;
      }
      .alert {
        margin-top: 5px;
        display:inline-block;
        vertical-align: middle;
        height: 50%;
        padding: 1px;
        margin-top: 1%;
        margin-bottom: 1%;
      }
  </style>

</head>

<body>

  <hr>
  <h3><strong>Detalle Sim</strong></h3>
  <hr>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="well form-horizontal col-md-8">

      <div class="row">
        <p class="col-md-4 text-left">
          <strong>Id: </strong>
          <%= @sim.id %>
        </p>
        <p class="user col-md-4 text-left">
          <strong>n° Serie: </strong>
          <%= @sim.serial_number %>
        </p>
        <p class=" user col-md-4 text-left">
          <strong>n° Teléfono: </strong>
          <%= @sim.phone_number %>
        </p>
      </div>

      <div class="row">
        <p class=" user col-md-4 text-left">
          <strong>Estado: </strong>
          <%= @sim.state %>
        </p>
        <p class="col-md-4 text-left">
          <strong>Disponible: </strong>
          <%= @sim.available %>
        </p>
        <p class=" user col-md-4 text-left">
          <strong>País: </strong>
          <%= @sim.country %>
        </p>
      </div>

      <hr>
      <%= link_to 'Editar', edit_sim_path(@sim) %> |
      <%= link_to 'Sims', sims_path %>

    </div>
    <div class="col-md-2"></div>
  </div>

  <% if notice %>
  <div class="row">
    <p class="col-md-4 text-left"></p>
    <p class="user col-md-4 alert alert-success">
         <strong> <%=notice%> </strong>
    </p>
    <p class=" user col-md-4 text-left"></p>
  </div>
  <% elsif alert %>
  <div class="row">
    <p class="col-md-2 text-left"></p>
    <p class="user col-md-8 alert alert-danger">
      <strong> Los siguientes errores impidieron finalizar la edición exitosamente: </strong>
      <% alert.each_pair do |k, v| %>
        <%= " | El campo "+k+" tiene el siguiente error: "+v[0] %>
      <% end %>
    </p>
    <p class=" user col-md-2 text-left"></p>
  </div>
  <% end %>

</body>
</html>