config/routes.rb
Rails.application.routes.draw do
  resources :plans
  resources :smartphones
  resources :users
  resources :sims
  resources :requests
  resources :bams

  # Home HomePage
  root to: 'home_pages#home'
  # Request Home
  get '/requests/home/menu' => 'home_pages#request_home'
  # Follow Request
  get '/requests/home/follow_request' => 'home_pages#follow_request'
  # Show Request for user
  get '/requests/home/follow' => 'requests#show'
  # Request FAQ
  get '/requests/home/faq' => 'home_pages#faq'
  # Request downloads
  get '/requests/home/downloads' => 'home_pages#downloads'
  # Request support
  get '/requests/home/support' => 'home_pages#support'


  # Validate User
  get '/requests/home/validate' => 'requests#validate_user'
  # Validates Aproval/reject of request
  get '/requests/validations/:id' => 'requests#validations'
  # Update request for supervisor
  patch '/requests/validations/update/:id' => 'requests#update_validation'

  # Delete Action
  # smp
  get '/smartphones/delete/:id' => 'smartphones#destroy'
  # bam
  get '/bams/delete/:id' => 'bams#destroy'
  # sim
  get '/sims/delete/:id' => 'sims#destroy'
  # plan
  get '/plans/delete/:id' => 'plans#destroy'

  # Requests Forms
  # TransferLine Form
  get '/requests/forms/transferline' => 'requests#transfer_line'
  # New Form
  get '/requests/forms/new' => 'requests#new_form'
  # Save New Form
  post '/requests/forms/create/new' => 'requests#create_user'
  # Renew Form
  get '/requests/forms/renew' => 'requests#renew_form'
  # Stolen or Lost Form
  get '/requests/forms/stolenlost' => 'requests#stolen_lost'
  # Technical Service Form
  get '/requests/forms/technicalservice' => 'requests#technical_service'

  # Download Nota de pedido
  # files
  get '/requests/files/:id' => 'requests#download_file'
  # Contract
  get '/requests/contracts/:id' => 'requests#download_contract'

  # Admin
  post 'admins/login_attempt' => 'sessions#login_attempt'
  get 'admins/login_attempt' => 'sessions#login'
  get 'admins/login' => 'sessions#login'
  get 'admins/logout' => 'sessions#logout'

  # routes to register an admin
  # post 'admins/new'=> 'admins#create'
  # get 'admins/signup' => 'admins#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :user
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  layout 'general_view', except: [:index, :show, :edit, :update, :new]
  layout 'admin_view', only: [:create]

  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  # Filter to protect page with login and session
  before_action :authenticate_user
  # check session timer
  before_action :session_expiry

  # GET /plans
  # GET /plans.json
  def index
    @search = Plan.search(params[:q])
    @plans  = @search.result
    @all_bp_roaming = all_bp_roaming
    @all_bp_roaming.unshift(['Todos',''])
    @all_p_bam = all_p_bam
    @all_p_bam.unshift(['Todos',''])

    render layout: 'admin_view'
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    render layout: 'admin_view'
  end

  # GET /plans/new
  def new
    @plan = Plan.new
    render layout: 'admin_view'
  end

  # GET /plans/1/edit
  def edit
    render layout: 'admin_view'
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan/Bolsa fue creado exitosamente' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { edirect_to new_plan_url, alert:  @plan.errors }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan/Bolsa fue editado exitosamente' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { redirect_to @plan, alert:  @plan.errors }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:item, :plan_type, :name, :price, :detail, :country, :category)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<style>
  .text_area {
    vertical-align: top;
  }
</style>

<%= form_with(model: plan, local: true) do |form| %>

<div class="row">
  <div class="col-md-2"></div>
  <div class="well form-horizontal col-md-8">

    <div class="row">
      <p class="col-md-1 text-left">
        <strong>Id: </strong>
      </p>
      <p class="col-md-3 text-left">
        <%= @plan.id %>
      </p>
      <p class="user col-md-1 text-left">
        <strong>Item: </strong>
      </p>
      <p class="user col-md-3">
        <%= form.select :item, [['Roaming','roaming'],['Bam', 'bam']],
        {}, {id: :plan_item, style: "width:120px", class: "pull-left"} %>
      </p>
      <p class=" user col-md-1 text-left">
        <strong>Tipo: </strong>
      </p>
      <p class=" user col-md-3">
        <%= form.select :plan_type, [['Plan','plan'],['Bolsa','bag']],
        {}, {id: :plan_plan_type, style: "width:120px", class: "pull-left"}%>
      </p>
    </div>

    <div class="row">
      <p class=" user col-md-1 text-left">
        <strong>Nombre: </strong>
      </p>
      <p class=" user col-md-3">
        <%= form.text_field :name, id: :plan_name, class: "pull-left",
        style: "width:180px" %>
      </p>
      <p class="col-md-1 text-left">
        <strong>Precio: </strong>
      </p>
      <p class=" user col-md-3">
        <%= form.number_field :price, id: :plan_price, class: "pull-left",
        style: "width:120px" %>
      </p>
      <p class=" user col-md-1 text-left">
        <strong>Categoría: </strong>
      </p>
      <p class=" user col-md-3">
        <%= form.select :category, [['Todas', 'ALL']],
        {}, {id: :plan_category, style: "width:120px", class: "pull-left"}%>
      </p>
    </div>

    <div class="row">
      <p class="user col-md-8 text-left">
        <strong>Descripción:</strong>
        <%= form.text_area :detail, id: :plan_detail, :rows => 4, :cols => 35,
        class: "text_area"%>
      </p>
      <p class="user col-md-1 text-left">
        <strong>País:</strong>
      </p>
      <p class=" user col-md-3">
        <%= form.select :country, [['Chile', 'CHL']],
        {}, {id: :plan_country, style: "width:120px", class: "pull-left"}%>
      </p>
    </div>

    <br>
    <div class="actions">
      <% if params[:action] == 'new'%>
        <%= form.submit 'Crear', onclick: "return confirm('Está seguro que desea Crear el Plan/Bolsa')",
        class: "btn btn-primary btn-md" %>
      <% else %>
        <%= form.submit 'Editar', onclick: "return confirm('Está seguro que desea Editar el Plan/Bolsa')",
        class: "btn btn-primary btn-md" %>
      <% end %>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>

<% end %>

app/views/plans/edit.html.erb
<hr>
<h3><strong>Editor Plan/Bolsa</strong></h3>
<hr>

<%= render 'form', plan: @plan %>

<%= link_to 'Plan/Bolsa', @plan %> |
<%= link_to 'Planes/Bolsas', plans_path %>

app/views/plans/index.html.erb
<style>
  .alert {
    margin-top: 5px;
    display:inline-block;
    vertical-align: middle;
    height: 50%;
    padding: 1px;
    margin-top: 1%;
    margin-bottom: 1%;
  }
  label {
    padding-top: 7px;
  }
  hr {
    margin-top: 3px;
    margin-bottom: 3px;
    padding: 0px;
  }
  h3 {
    margin-top: 12px;
    margin-bottom: 12px;
    padding: 0px;
  }
  .btn {
    margin-top: 10px;
    margin-bottom: 10px;
  }
</style>

<%= render partial: '/layouts/plan_filter' %>

<div class= "titulo">
  <hr>
  <h3><strong>Planes/Bolsas</strong></h3>
  <hr>
</div>

<% if notice %>
  <div class="row">
    <p class="col-md-4 text-left"></p>
    <p class="user col-md-4 alert alert-success">
         <strong> El Plan/Bolsa fue eliminado exitosamente </strong>
    </p>
    <p class=" user col-md-4 text-left"></p>
  </div>
<% end %>

<div class="container-fluid">
  <div class="table-responsive">
    <table class="table table-hover table-condensed">
      <thead class="thead-dark">
        <tr>
          <th scope="col" class= text-center><%= sort_link @search, :id, "id"%></th>
          <th scope="col" class= text-center><%= sort_link @search, :item, "Item"%> </th>
          <th scope="col" class= text-center><%= sort_link @search, :plan_type, "Tipo"%></th>
          <th scope="col" class= text-center>Nombre</th>
          <th scope="col" class= text-center>Plan</th>
          <th scope="col" class= text-center>Editar</th>
          <th scope="col" class= text-center>Eliminar</th>
        </tr>
      </thead>

      <tbody>
        <% @plans.each do |plan| %>
          <tr>
            <td><%= plan.id %></td>
            <td><%= plan.item %></td>
            <td><%= plan.plan_type %></td>
            <td><%= plan.name %></td>
            <td><%= link_to 'Plan/Bolsa', plan %></td>
            <td><%= link_to 'Editar', edit_plan_path(plan) %></td>
            <td><%= link_to 'Eliminar', '/plans/delete/'+plan.id.to_s,
            onclick: "return confirm('Está seguro que desea Eliminar el Plan/bolsa con id "+plan.id.to_s+ "')" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<hr>
<%= link_to 'Crear Plan/Bolsa', new_plan_path, class: "btn btn-primary btn-md" %>
<hr>
<br>

app/views/plans/new.html.erb
<hr>
<h3><strong>Crear Plan/Bolsa</strong></h3>
<hr>

<%= render 'form', plan: @plan %>

<% if alert %>
<div class="row">
  <p class="col-md-2 text-left"></p>
  <p class="user col-md-8 alert alert-danger">
    <strong> Los siguientes errores impidieron finalizar la creación exitosamente: </strong>
    <% alert.each_pair do |k, v| %>
      <%= " | El campo "+k+" tiene el siguiente error: "+v[0] %>
    <% end %>
  </p>
  <p class=" user col-md-2 text-left"></p>
</div>
<% end %>

<%= link_to 'Planes/Bolsas', plans_path %>

app/views/plans/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Solicitud Celulares CCU</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <style>
      p {
        margin: 1px 0px 1px 0px;
      }
      .alert {
        margin-top: 5px;
        display:inline-block;
        vertical-align: middle;
        height: 50%;
        padding: 1px;
        margin-top: 1%;
        margin-bottom: 1%;
      }
  </style>

</head>

<body>

  <hr>
  <h3><strong>Detalle Plan/Bolsa</strong></h3>
  <hr>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="well form-horizontal col-md-8">

      <div class="row">
        <p class="col-md-4 text-left">
          <strong>Id: </strong>
          <%= @plan.id %>
        </p>
        <p class="user col-md-4 text-left">
          <strong>Item: </strong>
          <%= @plan.item %>
        </p>
        <p class=" user col-md-4 text-left">
          <strong>Tipo: </strong>
          <%= @plan.plan_type %>
        </p>
      </div>

      <div class="row">
        <p class=" user col-md-4 text-left">
          <strong>Nombre: </strong>
          <%= @plan.name %>
        </p>
        <p class="col-md-4 text-left">
          <strong>Precio: </strong>
          <%= '$'+@plan.price.to_s %>
        </p>
        <p class=" user col-md-4 text-left">
          <strong>Categoría: </strong>
          <%= @plan.category %>
        </p>
      </div>

      <div class="row">
        <p class="user col-md-8 text-left">
          <strong>Descripción: </strong>
          <%= @plan.detail %>
        </p>
        <p class="user col-md-4 text-left">
          <strong>País: </strong>
          <%= @plan.country %>
        </p>
      </div>

      <hr>
      <%= link_to 'Editar', edit_plan_path(@plan) %> |
      <%= link_to 'Planes/Bolsas', plans_path %>

    </div>
    <div class="col-md-2"></div>
  </div>

  <% if notice %>
  <div class="row">
    <p class="col-md-4 text-left"></p>
    <p class="user col-md-4 alert alert-success">
         <strong> <%=notice%> </strong>
    </p>
    <p class=" user col-md-4 text-left"></p>
  </div>
  <% elsif alert %>
  <div class="row">
    <p class="col-md-2 text-left"></p>
    <p class="user col-md-8 alert alert-danger">
      <strong> Los siguientes errores impidieron finalizar la edición exitosamente: </strong>
      <% alert.each_pair do |k, v| %>
        <%= " | El campo "+k+" tiene el siguiente error: "+v[0] %>
      <% end %>
    </p>
    <p class=" user col-md-2 text-left"></p>
  </div>
  <% end %>

</body>
</html>